services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_chat_php
    volumes:
      - ./:/var/www/html
    environment:
      - DATABASE_URL=mysql://chatuser:chatpass@db:3306/chatdb
      - MERCURE_URL=http://mercure/.well-known/mercure
      - MERCURE_PUBLIC_URL=http://localhost:3000/.well-known/mercure
      - MERCURE_JWT_SECRET=!ChangeThisMercureHubJWTSecretKey!
    depends_on:
      - db
      - mercure
    networks:
      - chat_network

  nginx:
    image: nginx:alpine
    container_name: symfony_chat_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - chat_network

  db:
    image: mysql:8.0
    container_name: symfony_chat_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - chat_network

  mercure:
    image: dunglas/mercure
    container_name: symfony_chat_mercure
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8080
    ports:
      - "3000:80"
    networks:
      - chat_network

volumes:
  db_data:

networks:
  chat_network:
    driver: bridge