services:
  php:
    build: ./.docker/php
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: dev
    depends_on: []


  ws:
    build: ./.docker/php
    command: php /var/www/html/bin/console app:ws:serve
    volumes:
      - ./:/var/www/html
    depends_on:
      - php

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8000:80"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
    depends_on:
      - php
      - ws